[package]
name        = "rasterlab-cli"
description = "Command-line interface for RasterLab image processing"
version.workspace   = true
edition.workspace   = true
license.workspace   = true
rust-version.workspace = true

[[bin]]
name = "rasterlab"
path = "src/main.rs"

[dependencies]
rasterlab-core    = { workspace = true }
rasterlab-library = { workspace = true }

clap         = { workspace = true }
ctrlc        = { workspace = true }
libc         = { workspace = true }
serde_json   = { workspace = true }
rayon        = { workspace = true }
anyhow       = { workspace = true }

[dev-dependencies]
tempfile = "3"
